export { extract } from './core/extract.js';
export { countTokens } from './core/tokens.js';
export { scanInjections, aggressiveCompress } from './core/scrub.js';
export { fitToBudget } from './core/budget.js';
export { fitToContract, assertContract } from './core/contract.js';
export { proxyFetch } from './core/proxy.js';
export { fetchText } from './core/fetch.js';
export { extractBySchema } from './core/schema.js';
export { digestDelta, hashText } from './core/cache.js';
export { resolveTier, applyTier, TIERS, tierNames } from './core/tiers.js';
export { semanticDiff } from './core/diff.js';
export { dedup, detectLang } from './core/dedup.js';
export { SemanticCache } from './core/semcache.js';
export { multimodalDigest } from './core/multimodal.js';
export { PageRAG } from './core/rag.js';
export { spamScore } from './core/spam.js';
export { recommendModel } from './core/route.js';
export { DigestRegistry } from './core/cdn.js';
export { generateLlmsTxt } from './core/llms.js';
export { parseDeclaration, fetchDeclaration, sampleDeclaration } from './core/aidigest-txt.js';
export { costUsd, modelPrice, listModels, readStats, recordStats, summarizeStats } from './core/stats.js';
export { modelOutputPrice } from './core/stats.js';
export { adaptTask, resolveTask, taskNames, TASKS } from './core/tasks.js';
export { buildProvenance, renderSources } from './core/provenance.js';
export { assessQuality } from './core/quality.js';
export { redactSensitive } from './core/redact.js';
export { simulateSavings } from './core/savings.js';
export { HttpTextCache } from './core/httpcache.js';
export { normalizeSource, isReadableContentType } from './core/source.js';
export { buildContextMap, renderContextMap, parseContextMap, retrieveContext, expandContext } from './core/context.js';
export { buildEvidenceGraph, renderEvidenceSummary } from './core/evidence.js';
export { detectAcceleration, probeAcceleration } from './core/acceleration.js';
export { defaultAutomationFile, readAutomationConfig, writeAutomationConfig, createAutomationConfig, isAutomatic } from './core/automation.js';

export type { ExtractResult } from './core/extract.js';
export type { ProxyRequest, ProxyResponse } from './core/proxy.js';
export type { JsonSchemaLike } from './core/schema.js';
export type { TierName, TierProfile } from './core/tiers.js';
export type { DedupItem, DedupGroup } from './core/dedup.js';
export type { SharedDigest } from './core/cdn.js';
export type { SiteDeclaration } from './core/aidigest-txt.js';
export type { TaskMode, TaskProfile } from './core/tasks.js';
export type { Provenance, Citation } from './core/provenance.js';
export type { QualityReport } from './core/quality.js';
export type { RedactionKind, RedactionFinding, RedactionResult } from './core/redact.js';
export type { SavingsInput, SavingsResult } from './core/savings.js';
export type { CachedFetchResult } from './core/httpcache.js';
export type { SourceDocument, SourceKind } from './core/source.js';
export type { ContextBlock, ContextBlockKind, ContextMap, ContextRetrieval } from './core/context.js';
export type { EvidenceClaim, EvidenceLink, Contradiction, EvidenceGraph } from './core/evidence.js';
export type { AccelerationBackend, AccelerationInfo, AccelerationProbe } from './core/acceleration.js';
export type { OperationMode, AutomationConfig } from './core/automation.js';

